version: "3.7"
services:
  libreddit:
    container_name: libreddit
    image: spikecodes/libreddit:latest
    dns:
      - ${DNS_IP}
    ports:
      - ${APP_PORT}:8080
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.libreddit.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.libreddit.entrypoints: websecure
      traefik.http.routers.libreddit.service: libreddit
      traefik.http.routers.libreddit.tls.certresolver: myresolver
      traefik.http.services.libreddit.loadbalancer.server.port: 8080

